language: julia
os:
  - osx
  - linux
julia:
  - 1.0
  - nightly
notifications:
  email: false
addons:
  apt:
    packages:
    - hdf5-tools
env:
  global:
    - DATADEPS_ALWAYS_ACCEPT="true"
matrix:
  fast_finish: true
  allow_failures:
  - julia: nightly
  exclude:
  - julia: nightly
    os: osx
before_install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
  - julia --project=. -e 'using Pkg; Pkg.instantiate()'
  - export JULIA_TEST_GROUPS="unit integration"; julia --project=. -e 'using Pkg; Pkg.test("Boltzmann"; coverage=true)'
  - export JULIA_TEST_GROUPS="acceptance"; julia --project=. -e 'using Pkg; Pkg.test("Boltzmann")'
  #- export JULIA_TEST_GROUPS="benchmark"; julia --project=. -e 'using Pkg; Pkg.test("Boltzmann")'
after_success:
  - julia --project=. -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
